class CONFIG:
    def __init__(self):
        self.log_path = "log.txt"
        self.tokenizer_path = "D:\\pre-model\\biolinkbert"
        #self.tokenizer_path = "D:\\pre-model\\bert-case-chinese"
        self.model_config_path = "D:\\vscode-projects\\medical\\config\\model_config.json"
        self.device = "gpu"
        self.saved_model_path = "D:\\vscode-projects\\medical\\save_model"
        self.pretrained_model_path = "D:\\pre-model\\biolinkbert"
        #self.pretrained_model_path = "D:\\pre-model\\bert-case-chinese"
        self.test = True
        self.num_workers = 0
        # self.train_data_path = "D:\\vscode-projects\\medical\\dataset\\med-en\\MedQA\\data_clean\\questions\\US\\4_options\\phrases_no_exclude_train.jsonl"
        # self.dev_data_path = "D:\\vscode-projects\\medical\\dataset\\med-en\\MedQA\\data_clean\\questions\\US\\4_options\\phrases_no_exclude_dev.jsonl"
        # self.test_data_path = "D:\\vscode-projects\\medical\\dataset\\med-en\\MedQA\\data_clean\\questions\\US\\4_options\\phrases_no_exclude_test.jsonl"
        # self.train_data_path = "D:\\vscode-projects\\medical\\dataset\\zh\\train_mrc_topic.txt"
        # self.dev_data_path = "D:\\vscode-projects\\medical\\dataset\\zh\\dev_mrc_topic.txt"
        # self.test_data_path = "D:\\vscode-projects\\medical\\dataset\\zh\\test_mrc_topic.txt"
        # self.train_data_path = "D:\\vscode-projects\\medical\\dataset\\med-en\\bioasq\\train\\train_data2.json"
        # self.dev_data_path = "D:\\vscode-projects\\medical\\dataset\\med-en\\bioasq\\train\\val_data.json"
        # self.test_data_path = "D:\\vscode-projects\\medical\\dataset\\zh\\test_mrc_topic.txt"
        self.train_data_path = "D:\\vscode-projects\\medical\\dataset\\med-en\\bioasq\\train\\train_data.json"
        self.dev_data_path = "D:\\vscode-projects\\medical\\dataset\\med-en\\bioasq\\train\\val_data.json"
        self.test_data_path = "D:\\vscode-projects\\medical\\dataset\\zh\\test_mrc_topic.txt"
        self.test_size = 0.1
        self.batch_size=16
        self.epochs = 6
        self.lr=2e-5
        self.warmup_steps=2000
        self.log_step=1
        self.max_grad_norm=1.0
        self.gradient_accumulation=1
        self.topk=8
        self.test_max_len=20
        self.save_mode=True
        self.n_ctx=256
        self.num_classification=19
        self.together=False
